Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication1.Enum;

namespace WebApplication1.Models
{
    public class Player
    {
        private string name;
        private Roles role;
        private bool isReady = false;
        private int randomId;
        private int votes = 0;
        private bool isDead = false;

        public Player(string _name, Roles _role, bool _isReady,  int _id, int _votes, bool _isDead)
        {
            name = _name;
            role = _role;
            isReady = _isReady;
            isDead = _isDead;
            randomId = _id;
            votes = _votes;
        }

        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }


        public Roles Role
        {
            get
            {
                return role;
            }
            set
            {
                role = value;
            }
        }

        public bool IsReady
        {
            get
            {
                return isReady;
            }
            set
            {
                isReady = value;
            }
        }

        public int Votes
        {
            get
            {
                return votes;
            }
            set
            {
                votes = value;
            }
        }

        public int RandomId
        {
            get
            {
                return randomId;
            }
            set
            {
                randomId = value;
            }
        }

        public bool IsDead
        {
            get
            {
                return isDead;
            }
            set
            {
                isDead = value;
            }
        }
    }
}

Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data.Interfaces;
using WebApplication1.Enum;
using WebApplication1.Models;

namespace WebApplication1.Mocks
{
    public class PlayerController: Controller
    {
        private readonly IPlayer players;
        private readonly IEvent events;

        public PlayerController(IPlayer _players, IEvent _events)
        {
            players = _players;
            events = _events;
        }
        
        public ViewResult List()
        {
            IEnumerable<Player> list = players.Players;
            return View(list);
        }

        public IActionResult GetVote(string playerName)
        {
            string name = Request.Cookies["name"];
            bool Voted = bool.Parse(Request.Cookies["Voted"]);
            Player me = players.FindPlayer(name);
            Player player = players.FindPlayer(playerName);
            Event lastEvent = events.GetLastEvent();

            bool isDay = lastEvent.Type == EventType.Голосование_день;
            bool isNight = lastEvent.Type == EventType.Голосование_ночь;
            bool isMafia = me.Role == Roles.MAFIA;
            bool isDonMafia = me.Role == Roles.DON_MAFIA;

            if (isDay || (isNight && (isMafia || isDonMafia)))
            {
                if (!Voted && !me.IsDead && !player.IsDead)
                {
                    Database.SendQuery($"UPDATE Plaers set Votes = '{player.Votes + 1}' WHERE Name = '{playerName}'");
                    CookieOptions options = new CookieOptions();
                    Response.Cookies.Append("Voted", "True", options);
                }
            }
            return Redirect("list");
        }

        public ViewResult Game()
        {
            IEnumerable<Event> test = events.Events;
            var _players = players.Players;
            string name = Request.Cookies["name"];
            bool isPlayerBe = false;
            foreach (Player player in _players)
            {
                if (player.Name == name)
                {
                    isPlayerBe = true;
                    break;
                }
                else
                {
                    isPlayerBe = false;
                }
            }

            if (!isPlayerBe)
            {
                Random rnd = new Random();
                CookieOptions options = new CookieOptions();
                Response.Cookies.Append("Voted", "False", options);
                Database.SendQuery($"INSERT [Plaers] VALUES ('{name}', '{(int)Roles.PEOPLE}', 'False', '{rnd.Next(1000, 9999)}', '0', 'False')");
            }
            ViewData["event"] = events.EventFind(EventType.Старт);
            //DestroyAllInYourLife();
            return View(players.Players);
        }

        private async void DestroyAllInYourLife()
        {
            bool isGameEnded = false;
            while (!isGameEnded)
            {
                if (Request.Cookies["isGameEnded"] != "true")
                {
                    Task zadershka = Task.Delay(10 * 1000);
                    await zadershka;
                }
                else
                {
                    isGameEnded = true;
                }

            }
            Database.ClearTable("player");
            Database.ClearTable("events");
            Response.Cookies.Append("isGameEnded", "false");
            ReturnToIndex();
        }

        private ActionResult ReturnToIndex()
        {
            return Redirect("/Home/Index");
        }

        public IActionResult StartGame()
        {
            string name = Request.Cookies["name"];
            Database.SendQuery($"UPDATE Plaers set isReady = 'True' WHERE Name = '{name}'");
            bool isAllReady = true;
            var _players = players.Players;
            foreach (Player player in _players)
            {
                if (!player.IsReady)
                {
                    isAllReady = false;
                    break;
                }
                else
                {
                    isAllReady = true;
                }
            }

            if (isAllReady)
            {
                if (events.EventFind(EventType.Старт) == null)
                {
                    Database.SendQuery($"INSERT [Event] VALUES ('5', '{(int)EventType.Старт}', 'Game is started')");
                    DataTable currentPlayers = Database.SendQuery($"Select * from Plaers order by RandomId");
                    for (int i = 0; i < currentPlayers.Rows.Count; i++)
                    {
                        GenerateRoles(currentPlayers.Rows[i].ItemArray[1].ToString());
                    }
                }
            }

            return Redirect("game");
        }

        public ActionResult GetPlayer()
        {
            return PartialView(players.Players);
        }

        public void GenerateRoles(string name)
        {
            bool isGenerated = false;
            Random random = new Random();
            while (!isGenerated)
            {
                int randomNumber = random.Next(0, 10);
                (List<bool> mafiaIsBe, bool dommafiaIsBe, bool sherifIsBe) = CheckAllRoles();
                if (mafiaIsBe.Count < 2 && randomNumber < 3)
                {
                    SetRole(Roles.MAFIA, name);
                    isGenerated = true;
                }
                else if (!dommafiaIsBe && randomNumber >=3 && randomNumber < 6)
                {
                    SetRole(Roles.DON_MAFIA, name);
                    isGenerated = true;
                }
                else if (!sherifIsBe && randomNumber >= 6)
                {
                    SetRole(Roles.SHERIF, name);
                    isGenerated = true;
                }
                else if (dommafiaIsBe && sherifIsBe && mafiaIsBe.Count >= 2)
                {
                    isGenerated = true;
                }
            }
        }

        private void SetRole(Roles role, string name)
        {
            Database.SendQuery($"UPDATE Plaers set Rol ='{(int)role}' WHERE Name = '{name}'");
        }

        private (List<bool> mafiaIsBe, bool dommafiaIsBe, bool sherifIsBe) CheckAllRoles()
        {
            DataTable roles =  Database.SendQuery($"SELECT Rol From Plaers");
            //Player player = players.RolPlayers();
            List<bool> mafiaIsBe = new List<bool>();
            bool dommafiaIsBe = false;
            bool sherifIsBe = false;
            for (int i = 0; i < roles.Rows.Count; i++)
            {
                if (roles.Rows[i].ItemArray[0].ToString() == "0")
                {
                    mafiaIsBe.Add(true);
                }
                else if (roles.Rows[i].ItemArray[0].ToString() == "1")
                {
                    dommafiaIsBe = true;
                }
                else if (roles.Rows[i].ItemArray[0].ToString() == "2")
                {
                    sherifIsBe = true;
                }
            }
            return (mafiaIsBe, dommafiaIsBe, sherifIsBe);
        }
    }
}

Views/Player/Game.cshtml
@using WebApplication1.Models
@using WebApplication1.Data.Interfaces
@using WebApplication1.Mocks
@model IEnumerable<Player>

<p>Приветики-омлетики</p>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Mafia</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/Game_style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" />
</head>

<body>
    <div id="container">
        <div id="main" class="text-center">
            <iframe id="events" src="~/event/eventslist" height="90%" width="100%">ууууу</iframe>
        </div>
        <div id="players">
            <p>
                Игроки
            </p>
            <iframe src="~/player/list" height="90%" width="100%">ууууу</iframe>
            @{
                var events = Database.SendQuery($"SELECT * FROM [Event]").Rows;
            }
            @if (Model.Count() >= 1 && ViewData["event"] == null)
            {
                <a asp-controller="Player" asp-action="StartGame">Ну че собаки погнали</a>
            }
        </div>
    </div>

    <div id="chat" class="text-center">
        <form method="post" action="/Chat/AddMessage">
            <div class="text-center">
                <div lign="center">
                    <h2 class="text-center">Чат</h2>
                    <br />
                    <br />
                    <div class="input-group mb-2">
                        <div class="input-group-prepend">
                            <div class="input-group-text">Сообщение</div>
                        </div>
                        <input id="text" type="text" name="text" />
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <button class="btn btn-dark">Отправить</button>
                </div>
            </div>
        </form>
    </div>
</body>
</html>

Views/Player/List.cshtml
@using WebApplication1.Models
@model IEnumerable<Player>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{


                    foreach (var player in Model)
                    {
                    <p class="text-center" style="color:#000000">
                        <a asp-controller="Player" asp-action="GetVote" asp-route-playerName="@player.Name">@player.Name</a>
                    </p> }
 }

<script>
    setTimeout(function () {
        location.reload();
    }, 1500);
</script>